name: dependy_flutter
description: "Dependy Flutter is built on top of Dependy. It adds scoping features to help us manage dependencies within the widget
tree of our Flutter applications."
version: 1.0.2
homepage: https://github.com/xeinebiu/dependy

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dependy: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
