name: dependy
description: "Dependy is a lightweight and flexible dependency injection (DI) library for Dart. It simplifies the management of services and their dependencies."
version: 1.2.0
homepage: https://github.com/xeinebiu/dependy

environment:
  sdk: ^3.5.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
