name: dependy
description: "Dependy is a lightweight and flexible dependency injection (DI) library for Dart. It simplifies the management of services and their dependencies."
version: 1.4.0
homepage: https://github.com/xeinebiu/dependy

environment:
  sdk: ^3.6.0

resolution: workspace

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
