name: dependy
description: "Dependy is a lightweight and flexible dependency injection (DI) library for Dart. It simplifies the management of services and their dependencies, making your code more modular, maintainable, and testable."
version: 1.0.2
homepage: https://github.com/xeinebiu/dependy

environment:
  sdk: ^3.5.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
